"""initial schema

Revision ID: 0e91dfae838c
Revises: 
Create Date: 2026-02-22 12:58:53.617527
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e91dfae838c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('member_count', sa.BigInteger(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='serverplan'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_discord_id'), 'servers', ['discord_id'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_discord_id'), 'channels', ['discord_id'], unique=True)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_hash', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('kb_consent', sa.Boolean(), nullable=False),
    sa.Column('ai_consent', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_hash'), 'consent_records', ['user_hash'], unique=False)
    op.create_table('dataset_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('record_count', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('c2pa_manifest_hash', sa.String(length=128), nullable=True),
    sa.Column('pii_audit_hash', sa.String(length=128), nullable=True),
    sa.Column('consent_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_exports_server_id'), 'dataset_exports', ['server_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('discord_message_id', sa.String(length=32), nullable=False),
    sa.Column('author_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_to_id', sa.String(length=32), nullable=True),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_message_id')
    )
    op.create_index(op.f('ix_messages_author_hash'), 'messages', ['author_hash'], unique=False)
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_ids', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'RESOLVED', 'NOISE', 'INCOMPLETE', 'FAILED', name='threadstatus'), nullable=False),
    sa.Column('cluster_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checkpoint_thread_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkpoint_thread_id')
    )
    op.create_index(op.f('ix_threads_channel_id'), 'threads', ['channel_id'], unique=False)
    op.create_index(op.f('ix_threads_status'), 'threads', ['status'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('symptom', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('thread_summary', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_articles_language'), 'articles', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_language'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_threads_status'), table_name='threads')
    op.drop_index(op.f('ix_threads_channel_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_author_hash'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_dataset_exports_server_id'), table_name='dataset_exports')
    op.drop_table('dataset_exports')
    op.drop_index(op.f('ix_consent_records_user_hash'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_channels_discord_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_servers_discord_id'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ###
